stages:
  - build
  - deploy

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug


deployDebug:
  stage: deploy
  script:
    - scp /home/velikoborets//builds/HCmpKnjU/0/dudkevichvd/contactbook2/app/build/outputs/apk/debug/app-debug.apk -J f-droid@192.168.220.5 f-droid@172.20.220.11:/var/www/f-droid
    - ssh -J f-droid@192.168.220.5 f-droid@172.20.220.11 "cd /var/www/f-droid/ && fdroid update -c && fdroid update"
